$outputPath = Join-Path $PWD 'project_documentation_final.docx'
$word = New-Object -ComObject Word.Application
$word.Visible = $false
$doc = $word.Documents.Add()
$sel = $word.Selection

function Add-Heading($text, $level) {
    $sel.Style = "Heading $level"
    $sel.TypeText($text)
    $sel.TypeParagraph()
}

function Add-Paragraph($text) {
    $sel.Style = "Normal"
    $sel.TypeText($text)
    $sel.TypeParagraph()
}

function Add-Preformatted($text) {
    $sel.Font.Name = 'Courier New'
    $sel.Font.Size = 10
    $sel.TypeText($text)
    $sel.TypeParagraph()
    $sel.Font.Name = 'Calibri'
    $sel.Font.Size = 12
}

function Add-Table($rows, $cols, $values) {
    $table = $doc.Tables.Add($sel.Range, $rows, $cols)
    $table.Borders.Enable = 1
    for ($r = 1; $r -le $rows; $r++) {
        for ($c = 1; $c -le $cols; $c++) {
            $table.Cell($r, $c).Range.Text = $values[($r-1)*$cols + ($c-1)]
        }
    }
    $sel.MoveEnd()
    $sel.TypeParagraph()
}

# Title Page
$sel.Font.Name = 'Calibri'
$sel.Font.Size = 18
Add-Heading 'Sunrise Hotel Management System' 1
$sel.Font.Size = 14
Add-Paragraph 'Project Documentation'
Add-Paragraph 'Generated by automation for Eclipse Java hotel management project'
Add-Paragraph ('Date: ' + (Get-Date -Format 'yyyy-MM-dd'))
$sel.InsertBreak(7)

# Overview
Add-Heading '1. Project Overview' 2
Add-Paragraph 'The Sunrise Hotel Management System is a Java terminal application designed to manage hotel reservations, guest check-in/check-out, hotel service orders, admin price management, and invoice generation.'
Add-Paragraph 'The application is structured into well-defined packages across model, service, ui, util, and exception layers. It leverages OOP concepts such as encapsulation, inheritance, polymorphism, abstraction, and interface implementation.'
Add-Paragraph 'Key capabilities include:'
Add-Paragraph '• Remote room availability and reservation.'
Add-Paragraph '• Guest hotel service ordering for food, beverage, gym, and spa usage.'
Add-Paragraph '• Reception checkout that generates invoices using guest-filled service totals.'
Add-Paragraph '• Admin management of hotel service and product prices.'
$sel.InsertBreak(7)

# Package and Class Relationships
Add-Heading '2. Package and Class Relationships' 2
Add-Paragraph 'The project is organized into the following packages:'
$packagesTable = @(
    'Package', 'Class(es)',
    'model', 'Booking, Guest, Person, Staff, Room, RoomType, RoomStatus, Manageable',
    'service', 'HotelService, PriceList',
    'ui', 'ConsoleUI',
    'util', 'FileManager, Repository',
    'exception', 'HotelException, EntityNotFoundException, RoomNotAvailableException',
    'default', 'Main'
)
Add-Table 7 2 $packagesTable
Add-Paragraph 'The package relationships are as follows:'
Add-Preformatted @"
Main
  |
  +-- ConsoleUI
         |
         +-- HotelService
                 |
                 +-- Booking
                 +-- Room
                 +-- Guest
                 +-- Staff
                 +-- PriceList
                 +-- FileManager
                 +-- Repository

model relationships:
  Person <|-- Guest
  Person <|-- Staff
  Manageable <|-- Booking
  Manageable <|-- Room
  Room uses RoomType and RoomStatus

service relationships:
  HotelService orchestrates data access and business logic
  PriceList provides dynamic pricing for hotel services
"@
$sel.InsertBreak(7)

# Class responsibilities
Add-Heading '3. Class Responsibilities and Design' 2
Add-Paragraph 'This section explains the purpose of the main classes and how they interact.'
$classesTable = @(
    'Class', 'Responsibility', 'Relationship',
    'Main', 'Entry point that initializes the application and launches the console UI.', 'Uses ConsoleUI',
    'ConsoleUI', 'Terminal-based interface for guest, reception, and admin workflows.', 'Uses HotelService',
    'HotelService', 'Business logic layer for reservations, invoicing, and service orders.', 'Uses model classes and persistence utilities',
    'Booking', 'Represents individual hotel bookings and stores service usage.', 'References Guest and Room',
    'Guest', 'Stores guest identity, contact, and loyalty information.', 'Extends Person',
    'Staff', 'Stores staff identity and job details.', 'Extends Person',
    'Room', 'Models room availability, type, and status.', 'Implements Manageable',
    'PriceList', 'Manages dynamic item prices for food, beverages, gym and spa.', 'Used by HotelService',
    'FileManager', 'Handles CSV file persistence for rooms, guests, bookings, and staff.', 'Utility class used by HotelService',
    'Repository', 'Generic in-memory repository abstraction for data objects.', 'Used by FileManager and HotelService'
)
Add-Table 11 3 $classesTable
Add-Paragraph 'The application maintains loose coupling by separating UI, business logic, persistence, and model definitions into different packages.'
$sel.InsertBreak(7)

# OOP Concepts
Add-Heading '4. Object-Oriented Programming Concepts' 2
Add-Paragraph 'The following table describes the main OOP concepts applied in the project:'
$oopTable = @(
    'Concept', 'Definition', 'Project Usage',
    'Encapsulation', 'Hiding internal state and exposing controlled access through methods.', 'Model classes use private fields with getters and setters; HotelService controls state changes.',
    'Inheritance', 'Reusing common behavior through subclassing.', 'Guest and Staff inherit from abstract Person and share common identity properties.',
    'Polymorphism', 'Using a common interface or superclass to treat different types uniformly.', 'Manageable interface allows Room and Booking to expose common getSummary and validate behavior.',
    'Abstraction', 'Defining simple interfaces for complex behavior.', 'HotelService exposes reservation and checkout operations while hiding persistence details.',
    'Composition', 'Building complex objects from simpler ones.', 'Booking contains Guest and Room references, HotelService contains PriceList and repositories.',
    'Dynamic Binding', 'Resolving method calls at runtime based on object type.', 'Guest and Staff invoke Person behavior through inherited methods and support runtime type handling.'
)
Add-Table 7 3 $oopTable

Add-Heading '5. How OOP Concepts Are Used in Code' 2
Add-Paragraph 'In this project, OOP concepts are applied in the following detailed ways:'
Add-Paragraph '• Encapsulation stabilizes booking, room, and guest state by using private field access and validation in setters.'
Add-Paragraph '• Inheritance reduces duplication by allowing Guest and Staff to share common Person fields and validation logic.'
Add-Paragraph '• The Manageable interface abstracts summary and validation behavior across multiple entities.'
Add-Paragraph '• HotelService acts as a controller layer, separating user interaction from data operations and business rules.'
Add-Paragraph '• FileManager and Repository implement persistence using a composition-based storage approach.'

$wdFormatDocumentDefault = 16
$doc.SaveAs([ref] $outputPath, [ref] $wdFormatDocumentDefault)
$doc.Close()
$word.Quit()
Write-Output "DOCX-CREATED: $outputPath"
