$outDir = Join-Path $PWD 'docx_temp'
if (Test-Path $outDir) { Remove-Item -Recurse -Force $outDir }
New-Item -ItemType Directory -Path $outDir | Out-Null
New-Item -ItemType Directory -Path (Join-Path $outDir '_rels') | Out-Null
New-Item -ItemType Directory -Path (Join-Path $outDir 'word') | Out-Null

function Write-XmlFile($path, $content) {
  $bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
  [System.IO.File]::WriteAllBytes($path, $bytes)
}

$typesXml = @'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>
'@
Write-XmlFile (Join-Path $outDir '[Content_Types].xml') $typesXml

$relsXml = @'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>
'@
Write-XmlFile (Join-Path $outDir '_rels\.rels') $relsXml

$stylesXml = @'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:basedOn w:val="DefaultParagraphFont"/>
    <w:uiPriority w:val="1"/>
    <w:qFormat/>
  </w:style>
</w:styles>
'@
Write-XmlFile (Join-Path $outDir 'word\styles.xml') $stylesXml

$docXml = @'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>Sunrise Hotel Management System</w:t></w:r></w:p>
    <w:p><w:r><w:t>Project Documentation</w:t></w:r></w:p>
    <w:p><w:r><w:t>Generated by automation for Eclipse Java hotel management project</w:t></w:r></w:p>
    <w:p><w:r><w:t>Date: ' + (Get-Date -Format 'yyyy-MM-dd') + '</w:t></w:r></w:p>
    <w:p><w:r><w:br w:type="page"/></w:r></w:p>

    <w:p><w:r><w:t>1. Project Overview</w:t></w:r></w:p>
    <w:p><w:r><w:t>The Sunrise Hotel Management System is a Java terminal application built to manage room reservations, guest hotel services, receptionist checkout, admin pricing, and invoice generation.</w:t></w:r></w:p>
    <w:p><w:r><w:t>It is designed around modular packages for model definitions, service logic, user interaction, persistence utilities, and exception handling.</w:t></w:r></w:p>
    <w:p><w:r><w:t>Core features include remote room reservation, guest hotel service ordering, reception checkout using guest-filled usage data, and admin price management.</w:t></w:r></w:p>
    <w:p><w:r><w:t>Key capabilities:</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Remote room availability and reservation.</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Guest service selection for food, beverages, gym, and spa.</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Reception checkout invoice generation based on guest service totals.</w:t></w:r></w:p>
    <w:p><w:r><w:t>• Admin management of service prices through a dynamic price list.</w:t></w:r></w:p>
    <w:p><w:r><w:br w:type="page"/></w:r></w:p>

    <w:p><w:r><w:t>2. Package and Class Relationships</w:t></w:r></w:p>
    <w:p><w:r><w:t>The project is structured into the following packages:</w:t></w:r></w:p>
    <w:tbl>
      <w:tr><w:tc><w:p><w:r><w:t>Package</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Classes</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>model</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Booking, Guest, Person, Staff, Room, RoomType, RoomStatus, Manageable</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>service</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>HotelService, PriceList</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>ui</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>ConsoleUI</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>util</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>FileManager, Repository</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>exception</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>HotelException, EntityNotFoundException, RoomNotAvailableException</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>default</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Main</w:t></w:r></w:p></w:tc></w:tr>
    </w:tbl>

    <w:p><w:r><w:t>UML-style class relationship diagram:</w:t></w:r></w:p>
    <w:p><w:r><w:t>Main -> ConsoleUI -> HotelService</w:t></w:r></w:p>
    <w:p><w:r><w:t>HotelService -> Booking, Room, Guest, Staff, PriceList, FileManager, Repository</w:t></w:r></w:p>
    <w:p><w:r><w:t>Guest and Staff extend Person</w:t></w:r></w:p>
    <w:p><w:r><w:t>Room and Booking implement Manageable</w:t></w:r></w:p>
    <w:p><w:r><w:t>Room uses RoomType and RoomStatus enums</w:t></w:r></w:p>

    <w:p><w:r><w:br w:type="page"/></w:r></w:p>

    <w:p><w:r><w:t>3. Class Responsibilities and Relationships</w:t></w:r></w:p>
    <w:p><w:r><w:t>The following table summarizes each main class and its role in the application.</w:t></w:r></w:p>
    <w:tbl>
      <w:tr><w:tc><w:p><w:r><w:t>Class</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Responsibility</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Relationship</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Main</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Application entry point that launches ConsoleUI.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Uses ConsoleUI</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>ConsoleUI</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Terminal interface for reservation, service ordering, reception checkout, and admin operations.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Uses HotelService</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>HotelService</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Business layer responsible for booking logic, checkout invoices, and price management.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Coordinates model and utility classes</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Booking</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Represents reservations and stores hotel service usage quantities.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>References Guest and Room</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Guest</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Stores guest information and loyalty-related data.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Extends Person</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Staff</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Stores hotel staff identity and position details.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Extends Person</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Room</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Models room type, status, and availability.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Implements Manageable</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>PriceList</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Stores dynamic prices for food, beverages, gym, and spa items.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Used by HotelService</w:t></w:r></w:p></w:tc></w:tr>
    </w:tbl>

    <w:p><w:r><w:br w:type="page"/></w:r></w:p>

    <w:p><w:r><w:t>4. Object-Oriented Programming Concepts</w:t></w:r></w:p>
    <w:tbl>
      <w:tr><w:tc><w:p><w:r><w:t>Concept</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Definition</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Project Usage</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Encapsulation</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Hiding internal state and exposing controlled access.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Private fields with getters/setters in model classes; validation in setters.</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Inheritance</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Reusing common behavior through subclassing.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Guest and Staff extend Person and inherit shared identity behavior.</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Polymorphism</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Using a common interface or superclass for multiple object types.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Booking and Room implement Manageable, allowing uniform handling in lists and summaries.</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Abstraction</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Exposing only essential behavior while hiding implementation details.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>HotelService exposes reservation, checkout, and service methods without revealing persistence details.</w:t></w:r></w:p></w:tc></w:tr>
      <w:tr><w:tc><w:p><w:r><w:t>Composition</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Building objects from other objects.</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Booking contains Guest and Room references; HotelService contains PriceList and repository references.</w:t></w:r></w:p></w:tc></w:tr>
    </w:tbl>

    <w:p><w:r><w:t>5. OOP Application Summary</w:t></w:r></w:p>
    <w:p><w:r><w:t>The project uses OOP to separate concerns, keep data models clean, and make service logic reusable and maintainable.</w:t></w:r></w:p>
    <w:p><w:r><w:t>By using inheritance and interfaces, the system reduces duplication while supporting flexible extension of guest, staff, and room behaviors.</w:t></w:r></w:p>
    <w:p><w:r><w:t>The architecture keeps UI, business logic, persistence, and domain models decoupled, which helps in future expansion and testing.</w:t></w:r></w:p>

    <w:p><w:r><w:br w:type="page"/></w:r></w:p>
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
    </w:sectPr>
  </w:body>
</w:document>
'@
Write-XmlFile (Join-Path $outDir 'word\document.xml') $docXml

$outFile = Join-Path $PWD 'project_documentation_final.docx'
if (Test-Path $outFile) { Remove-Item $outFile -Force }

$zipFile = Join-Path $PWD 'project_documentation_final.zip'
if (Test-Path $zipFile) { Remove-Item $zipFile -Force }
Compress-Archive -Path (Join-Path $outDir '*') -DestinationPath $zipFile -Force
Rename-Item -Path $zipFile -NewName (Split-Path $outFile -Leaf)
Remove-Item -Recurse -Force $outDir
Write-Output "DOCX-CREATED: $outFile"
